apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::248189947068:role/sas-6881323-default-eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::248189947068:role/osintube-codebuild-role
      username: codebuild
    - rolearn: arn:aws:iam::248189947068:role/eksctl-sas-6881323-eks-nodegroup-k-NodeInstanceRole-8kNMFCxEK784
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::248189947068:user/roberto.diniz-2
      username: roberto.diniz-2
      groups:
        - system:authenticated
