apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: s3-sink-connector
  namespace: lab
spec:
  class: "io.confluent.connect.s3.S3SinkConnector"
  taskMax: 1
  connectClusterRef:
    name: kafka-connect-proper
  configs:
    topics: "playground-topic"
    s3.region: "sa-east-1"
    s3.bucket.name: "s33ding-kafka-output"
    s3.part.size: "5242880"
    flush.size: "3"
    rotate.interval.ms: "10000"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    partitioner.class: "io.confluent.connect.storage.partitioner.TimeBasedPartitioner"
    partition.duration.ms: "3600000"
    path.format: "year=YYYY/month=MM/day=dd/hour=HH"
    locale: "en-US"
    timezone: "America/Sao_Paulo"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
