apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-connect-sa
  namespace: lab
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::248189947068:role/kafka-connect-s3-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-connect-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-connect-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafka-connect-role
subjects:
- kind: ServiceAccount
  name: kafka-connect-sa
  namespace: lab
