apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      tolerations:
      - key: "lab"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        role: "lab"
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: testdb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        - name: postgres-conf
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        args: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
      volumes:
      - name: init-sql
        configMap:
          name: postgres-init
      - name: postgres-conf
        configMap:
          name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: lab
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: lab
data:
  init.sql: |
    CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100), email VARCHAR(100));
    CREATE TABLE orders (id SERIAL PRIMARY KEY, user_id INT, product VARCHAR(100), amount DECIMAL(10,2));
    INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');
    INSERT INTO orders (user_id, product, amount) VALUES (1, 'Laptop', 999.99);
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: lab
data:
  postgresql.conf: |
    listen_addresses = '*'
    port = 5432
    wal_level = logical
    max_wal_senders = 10
    max_replication_slots = 10
    shared_preload_libraries = 'pg_stat_statements'
